{"success":false,"error":"Error 111 connecting to localhost:6380. Connection refused.","error_code":"INTERNAL_ERROR","api_version":"v1","timestamp":"2025-10-04T07:56:54.863744","details":{"action":"get_firs_connection_status"}}